---
title: "CS350 Networks of Software and Developers"
author: "Riccardo Romio"
date: "2022-12-15"
output: html_document
---

```{r}
library(ctv)
library(tidyverse)
library(RWsearch)
library(tm)
library(SnowballC)
crandb_down()
```

```{r}
taskViews = ctv::available.views()

#random stuff past this point in the block
taskViewNames = c()
len = length(taskViews)
len
for(i in (1:len)){
  taskViewNames = append(taskViewNames, unlist(taskViews[i])[1])
}
```

```{r}
#Example of how to filter by core
filter(taskViews$Agriculture$packagelist, core == TRUE)
filter(taskViews$Agriculture)
```

```{r} 
#Function for getting description files covering edge cases where there may not be any packages in a TV or a package has no description file
getDesc = function(tv, coreCheck){
  temp = taskViews[[tv]]
  temp2 = filter(temp$packagelist, core == coreCheck)$name
  if(length(temp2) == 0){
    return(data.frame(taskView = c(), packages = c(), description = c()))
  }
  descArr = c()
  counter = 0
  for(i in temp2){
    descTemp = filter(crandb, Package == i)$Description
    if(length(descTemp) == 0){
      descTemp = ""
    }
    descArr = append(descArr, descTemp)

  }
  return(data.frame(taskView = tv, packages = temp2, description = descArr))
}
```

```{r}
#Test that the function above works
MLTVDesc = getDesc("MachineLearning", FALSE)
``` 

```{r}
#gathering all desc files
allDescCore = data.frame(taskView = c(), packages = c(), description = c())
for(i in taskViewNames){
  allDescCore = rbind(allDescCore, getDesc(i, FALSE))
}
```

```{r}
#Starting the data cleaning process
vec = allDescCore$description
corpus = Corpus(VectorSource(vec))
corpus = tm_map(corpus, content_transformer(tolower))
corpus = tm_map(corpus, removeNumbers)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, stopwords("english"))
corpus = tm_map(corpus, stemDocument)
corpus = tm_map(corpus, stripWhitespace)
as.character(corpus[[1]])
```

```{r}
#Creating the bag of words
dtm = DocumentTermMatrix(corpus)
dtm = removeSparseTerms(dtm, 0.99)
finalDataSet = as.data.frame(as.matrix(dtm))
```



